Repository knaxus/problem-solving-javascript, pull requests merged in 2019-10, with the labels that each got.

#28 max-product-of-3-numbers error throw
  src/_Problems_/max-product-of-3-numbers/index.js
Labels: Hacktoberfest, bug-fix

#29 add find-2nd-max tests
  src/_Problems_/find-2nd-max/index.js
  src/_Problems_/find-2nd-max/index.test.js
Labels: Hacktoberfest, review done

#30 add subsequence tests
  src/_Problems_/get_subsequence/index.js
  src/_Problems_/get_subsequence/subsequence.test.js
Labels: Hacktoberfest, review done

#25 Add test for next greater element
  src/_Problems_/next-greater-element/index.js
  src/_Problems_/next-greater-element/next-greater-element.test.js
Labels: Hacktoberfest, review done

#23 Add test for string permutation
  README.md
  src/_Problems_/get-string-permutations/get-string-permutations.test.js
  src/_Problems_/get-string-permutations/index.js
  src/_Problems_/get_string_permutations/index.js
Labels: Hacktoberfest, review done

#20 Added Reverse Linked List Problem.
  README.md
  src/_DataStructures_/LinkedList/reverse-linked-list/index.js
  src/_DataStructures_/LinkedList/reverse-linked-list/reverse-linked-list.test.js
Labels: Hacktoberfest, review done

#31 balanced-parenthesis
  README.md
  src/_DataStructures_/Stack/balanced-parenthesis/index.js
  src/_DataStructures_/Stack/index.js
Labels: Hacktoberfest, review done

#26 Add unit tests to Max Product of 3 numbers problem
  src/_Problems_/max-product-of-3-numbers/index.js
  src/_Problems_/max-product-of-3-numbers/max-product-of-3-numbers.test.js
Labels: Hacktoberfest, review done

#37 Implementation of finding the smallest common number
  README.md
  src/_Problems_/get-smallest-common-number/index.js
Labels: Hacktoberfest, beginner friendly, review done

#36 Implementation of 2 stacks using 1 array
  README.md
  src/_DataStructures_/Stack/2-stacks-using1-array/index.js
Labels: bug-fix, enhancement, new problem, review done

#33 Added postfix expression evaluation problem
  README.md
  src/_Classics_/fibonacci/index.js
  src/_DataStructures_/Stack/postfix-expression-evaluation/index.js
  src/_DataStructures_/Stack/remove-consecutive-repeated-digits/index.js
Labels: Hacktoberfest, beginner friendly, changes requested, under review

#45 Add Suffix Tree
  README.md
  src/_DataStructures_/SuffixTree/index.js
Labels: Hacktoberfest, new problem, review done

#32 doubly link list
  README.md
  src/_Algorithms_/lru-cache/index.js
  src/_DataStructures_/DoublyLinkedList/index.js
Labels: Hacktoberfest, changes requested, under review

#49 Added BST
  README.md
  src/_DataStructures_/Trees/BST/Node.js
  src/_DataStructures_/Trees/BST/index.js
  src/_DataStructures_/Trees/SuffixTree/index.js
Labels: New Data Structure, strict review

#50 Unit Test for Get Smallest Common Number
  src/_Problems_/get-smallest-common-number/get-smallest-common-number.test.js
Labels: Hacktoberfest, under review

#56 delete() & enhancements in BST
  src/_DataStructures_/Trees/BST/index.js
Labels: New Data Structure, changes requested, enhancement, review done, strict review

#52 return list instead of console.log
  src/_DataStructures_/DoublyLinkedList/index.js
Labels: Hacktoberfest, bug-fix, review done

#59 Add unit tests to postfix expression evaluation function. Resolves #34
  src/_DataStructures_/Stack/postfix-expression-evaluation/index.js
  src/_DataStructures_/Stack/postfix-expression-evaluation/postfix-expression-evaluation.test.js
Labels: Hacktoberfest

#53 Adds testing for the get mazePath problem #48
  README.md
  src/_Problems_/get-mazePath/get-mazePath.test.js
  src/_Problems_/get-mazePath/index.js
Labels: Hacktoberfest

#62 New Problem: kth max & min in BST
  README.md
  src/_DataStructures_/Trees/BinarySearchTree/Node.js
  src/_DataStructures_/Trees/BinarySearchTree/find-kth-max/index.js
  src/_DataStructures_/Trees/BinarySearchTree/find-kth-min/index.js
  src/_DataStructures_/Trees/BinarySearchTree/index.js
Labels: new problem, review done

#55 Fix Fibonacci problem for negative numbers
  README.md
  src/_Classics_/fibonacci/index.js
  src/_DataStructures_/Queue/index.js
Labels: Hacktoberfest, bug-fix, under review

#77 Add tests for LRUCache
  src/_Algorithms_/lru-cache/LRUCache.test.js
  src/_Algorithms_/lru-cache/index.js
Labels: Hacktoberfest

#79 Enhancements on Linked lists
  src/_DataStructures_/LinkedList/index.js
Labels: enhancement

#80 Re-implementation of Queue
  src/_DataStructures_/LinkedList/index.js
  src/_DataStructures_/Queue/Queue.test.js
  src/_DataStructures_/Queue/QueueUsingArray.js
  src/_DataStructures_/Queue/index.js
  src/_DataStructures_/Queue/weave/index.js
  src/_DataStructures_/Queue/weave/weave.test.js
Labels: New Data Structure, enhancement, strict review

#78 Add jumpSearch and Tests
  src/_Searching_/JumpSearch/JumpSearch.test.js
  src/_Searching_/JumpSearch/index.js
Labels: Hacktoberfest, changes requested

#85 Added sort a stack problem and solution.
  README.md
  src/_DataStructures_/Stack/sort-a-stack/index.js
Labels: Hacktoberfest, under review

#86 BST unit test for delete()
  src/_DataStructures_/Trees/BinarySearchTree/BinarySearchTree.test.js
Labels: Hacktoberfest, review done

#67 BST unit tests added for insert()
  src/_DataStructures_/Trees/BinarySearchTree/BinarySearchTree.test.js
Labels: Hacktoberfest, review done

#69 Added tests for BST insertion
  src/_DataStructures_/Trees/BinarySearchTree/bst-insertion.test.js
Labels: Hacktoberfest, changes requested, under review

#91 LCA implementation (fixes #89)
  src/_DataStructures_/Trees/BinarySearchTree/lowest-common-ancestor/index.js
  src/_DataStructures_/Trees/BinarySearchTree/lowest-common-ancestor/index.test.js
Labels: Hacktoberfest, new problem, under review

#94 Added factorial problem and solution
  src/_Problems_/factorial/index.js
  src/_Problems_/factorial/index.test.js
Labels: Hacktoberfest

#76 Add Ternary search
  src/_Searching_/TernarySearch/TernarySearch.test.js
  src/_Searching_/TernarySearch/index.js
Labels: Hacktoberfest, changes requested, new problem, under review

#73 Added test cases for BST deletion #66
  src/_DataStructures_/Trees/BinarySearchTree/bst-deletion.test.js
Labels: Hacktoberfest, beginner friendly, review done

#96 Added Binary Tree
  README.md
  src/_DataStructures_/Trees/BinaryTree/Node.js
  src/_DataStructures_/Trees/BinaryTree/index.js
Labels: New Data Structure, enhancement, under review

#102 Changes in Linked Lists
  src/_DataStructures_/DoublyLinkedList/index.js
  src/_DataStructures_/LinkedList/index.js
Labels: enhancement

#100 Added tests for the A* algorithm and cleaned up A* directories
  src/_PathFinder_/AStar/AStar.test.js
  src/_PathFinder_/AStar/index.js
Labels: Hacktoberfest, enhancement, under review, unit-test-aaded

#104 Trie - tree based data structure
  README.md
  src/_DataStructures_/Trees/Trie/Node.js
  src/_DataStructures_/Trees/Trie/index.js
Labels: New Data Structure, enhancement

#109 change: the data part should be named as my_data
  src/_DataStructures_/LinkedList/index.js
Labels: enhancement

#123 Adding Check if a binary tree is subtree of another binary tree
  src/_DataStructures_/Trees/BinaryTree/check-binary-tree-subtree-another-binary-tree/index.js
Labels: Hacktoberfest, review done

#117 Trie problems
  README.md
  src/_DataStructures_/Trees/Trie/Node.js
  src/_DataStructures_/Trees/Trie/all-words-in-trie/index.js
  src/_DataStructures_/Trees/Trie/get-unique-words/index.js
  src/_DataStructures_/Trees/Trie/index.js
  src/_DataStructures_/Trees/Trie/total-words-in-trie/index.js
  src/_DataStructures_/Trees/Trie/unique-word-count/index.js
Labels: enhancement, new problem, review done, strict review

#129 postfix-expression-evaluation #61
  src/_DataStructures_/Stack/postfix-expression-evaluation/index.js
  src/_DataStructures_/Stack/postfix-expression-evaluation/postfix-expression-evaluation.test.js
Labels: Hacktoberfest, bug-fix, new problem, under review, unit-test-aaded

#131 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: enhancement

#101 --update : path change of A* algo
  README.md
  src/_Algorithms_/path-finder/a-star/index.js
Labels: enhancement

#138 Add unit tests for Trie/unique-word-count
  src/_DataStructures_/Trees/Trie/unique-word-count/index.js
  src/_DataStructures_/Trees/Trie/unique-word-count/index.test.js
Labels: Hacktoberfest

#130 Adding bottom view binary tree problem solution
  .gitignore
  src/_DataStructures_/Trees/BinaryTree/bottom-view-binary-tree/index.js
Labels: changes requested

#139 Added Unit Tests to Total Words in Tries closes #136
  src/_DataStructures_/Trees/Trie/total-words-in-trie/total-words-in-trie.test.js
Labels: Hacktoberfest, review done, unit-test-aaded

#141 Update total-words-in-trie.test.js
  src/_DataStructures_/Trees/Trie/total-words-in-trie/total-words-in-trie.test.js
Labels: unit-test-fix

#127 Implement Binary Tree to Binary Search Tree Conversion - Solution
  src/_DataStructures_/Trees/BinaryTree/index.js
  src/_Problems_/binary-tree-to-binary-search-tree/binary-tree-to-binary-search-tree.test.js
  src/_Problems_/binary-tree-to-binary-search-tree/index.js
Labels: Hacktoberfest, changes requested, review partially done, under review

#147 add test for bottom view binary tree
  src/_DataStructures_/Trees/BinaryTree/bottom-view-binary-tree/BottomViewBinaryTree.test.js
Labels: Hacktoberfest, review done

#150 Changed some minor typos in Contributing.md
  CONTRIBUTING.md
Labels: Hacktoberfest, review done

#142 Increase code coverage
  src/_DataStructures_/DoublyLinkedList/Node.js
  src/_DataStructures_/DoublyLinkedList/doublyLinkedList.test.js
  src/_DataStructures_/DoublyLinkedList/index.js
  src/_DataStructures_/LinkedList/LinkedList.test.js
  src/_DataStructures_/Queue/Queue.test.js
  src/_DataStructures_/Stack/postfix-expression-evaluation/index.js
  src/_DataStructures_/Stack/postfix-expression-evaluation/postfix-expression-evaluation.test.js
  src/_DataStructures_/Trees/BinarySearchTree/BinarySearchTree.test.js
  src/_DataStructures_/Trees/BinarySearchTree/bst-isEmpty.test.js
  src/_DataStructures_/Trees/BinarySearchTree/bst-maximum.test.js
  src/_DataStructures_/Trees/BinarySearchTree/bst-minimum.test.js
  src/_DataStructures_/Trees/BinarySearchTree/bst-remove.test.js
  src/_DataStructures_/Trees/BinarySearchTree/bst-search.test.js
  src/_DataStructures_/Trees/BinarySearchTree/height-of-bst/height-of-bst.test.js
  src/_DataStructures_/Trees/BinarySearchTree/index.js
  src/_DataStructures_/Trees/BinarySearchTree/lowest-common-ancestor/index.js
  src/_DataStructures_/Trees/BinarySearchTree/lowest-common-ancestor/index.test.js
  src/_DataStructures_/Trees/Trie/total-words-in-trie/total-words-in-trie.test.js
  src/_PathFinder_/AStar/AStar.test.js
  src/_PathFinder_/AStar/index.js
  src/_Problems_/anagrams/anagrams.test.js
  src/_Problems_/get-smallest-common-number/get-smallest-common-number.test.js
  src/_Problems_/get-smallest-common-number/index.js
  src/_Searching_/JumpSearch/JumpSearch.test.js
  src/_Searching_/JumpSearch/index.js
  src/_Searching_/TernarySearch/TernarySearch.test.js
  src/_Searching_/TernarySearch/index.js
Labels: Hacktoberfest, bug-fix, changes requested, enhancement, strict review, under review, unit-test-fix

#149 test: add test for get-unique-words
  src/_DataStructures_/Trees/Trie/get-unique-words/get-unique-words.test.js
Labels: Hacktoberfest, changes requested, under review, unit-test-aaded

#148 test: add test for all-words-in-tree
  src/_DataStructures_/Trees/Trie/all-words-in-trie/all-words-in-trie.test.js
  src/_DataStructures_/Trees/Trie/all-words-in-trie/index.js
Labels: Hacktoberfest, changes requested, under review, unit-test-aaded
